### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@foobar.team",
  "password": "123456"
}

> {%
 client.global.set("auth_token", response.body.token)
 %}

### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "phone": "{{phone}}"
}

> {%
 client.global.set("session_id", response.body.session_id)
 %}

### Verify
POST {{host}}/api/auth/verify
Content-Type: application/json

{
  "session_id": "{{session_id}}",
  "verification_code": "209344"
}

> {% client.global.set("auth_token", response.body.token); %}

### Logout
POST {{host}}/api/logout
Authorization: Bearer {{auth_token}}

### Users list
GET {{host}}/api/users
Authorization: Bearer {{auth_token}}
